# ========== Perfil Activo (Viene del .env) ==========
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
dotenv.enabled=true

# ========== Configuración Global de App ==========
spring.application.name=ecommerce-backend
server.port=8080
server.servlet.context-path=

# ========== Flyway ==========
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ========== App Custom (Usando variables) ==========
app.backend.base-url=${BACKEND_BASE_URL:http://localhost:8080}
app.mail.from=${MAIL_FROM:noreply@hornerotech.com.ar}
app.mail.subject.verify=Verifica tu cuenta
app.admin.email=hornerotech@gmail.com
app.cookie.domain=${app.cookie.domain:hornerotech.com.ar}

# ========== JWT ==========
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ========== Mercado Pago ==========
mp.access-token=${MP_ACCESS_TOKEN}
mp.webhook-url=${MP_WEBHOOK_URL}
mp.webhook-secret=${MP_WEBHOOK_SECRET}
front.base-url=${FRONT_BASE_URL:http://localhost:3000}

# ========== Resend ==========
resend.api-key=${RESEND_API_KEY}

# ========== Meta Pixel ==========
META_PIXEL_ID=${META_PIXEL_ID}
META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
meta.test-mode=${meta.test-mode:false}
META_TEST_CODE=${META_TEST_CODE}

# ========== OAuth2 Google ==========
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# ========== OAuth2 Azure / Microsoft ==========
spring.security.oauth2.client.registration.azure.client-id=${AZURE_CLIENT_ID}
spring.security.oauth2.client.registration.azure.client-secret=${AZURE_CLIENT_SECRET}
spring.security.oauth2.client.registration.azure.scope=openid,profile,email,User.Read
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.azure.redirect-uri={baseUrl}/login/oauth2/code/azure
spring.security.oauth2.client.registration.azure.client-name=Microsoft

spring.security.oauth2.client.provider.azure.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.azure.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.azure.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.azure.user-name-attribute=sub

AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
