# Base de Datos Remota (Tomada del .env)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Reparar Flyway (Checksum mismatch V5)
spring.flyway.validate-on-migrate=false

# Reparar Flyway (Checksum mismatch V5)
spring.flyway.validate-on-migrate=false
