# Base de Datos Local
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_qa
spring.datasource.username=postgres
spring.datasource.password=4964

# Hibernación
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
